#! /bin/bash

name=$1
starts=$2
ends=$3

eval mkdir $name{$starts..$ends}

Output1:
sh flm.sh devops 1 5
devops1
devops2
devops3
devops4
devops5

Output2:
sh flm.sh
{..}

Output3:
sh flm.sh sudhan 1 3
sudhan1
sudhan2
sudhan3

----------------------------------------------------------------

#! /bin/bash

name=$1
starts=$2
ends=$3

mkdir $name{$starts..$ends}

Output1:
sh flm.sh devops 1 5
devops{1..5}

Output2:
sh flm.sh
{..}

Output3:
sh flm.sh sudhan 1 10
sudhan{1..10}
