#! /bin/bash
echo "I learned SCM tool as "$1
echo "I learned CI/CD tool as "$2
echo "I learned containerization tool as "$3
echo "I worked on IAC tool called "$4
echo "Now my Tech Stack are "$@
echo "All the values are present in "$0

Command:
./flm.sh GIT Jenkins Docker Terraform

Output:
I learned SCM tool as GIT
I learned CI/CD tool as Jenkins
I learned containerization tool as Docker
I worked on IAC tool called Terraform
Now my Tech Stack are GIT Jenkins Docker Terraform
All the values are present in ./flm.sh
