#! /bin/bash
echo "Enter your age:"
read age

if [[ $age -le 18 ]];
then
        echo "Not eligible for Vote!"
else
        echo "Eligible for Vote:)"
fi


Output1:
Enter your age:
12
Not eligible for Vote!

Output2:
Enter your age:
54
Eligible for Vote:)
