#! /bin/bash
echo "Enter your score:"
read score

if [[ $score -eq 100 ]];
then
        echo "You got 3rd Prize"
elif [[ $score -eq 200 ]];
then
        echo "You got 2nd Prize"
elif [[ $score -eq 300 ]];
then
        echo "You got 1st Prize"
else
        echo "Better luck next time"
fi


Output1:
Enter your score:
100
You got 3rd Prize

Output2:
Enter your score:
200
You got 2nd Prize

Output3:
Enter your score:
300
You got 1st Prize

Output4:
Enter your score:
400 
Better luck next time
