#! /bin/bash
echo "Enter your Email:"
read email

if [[ $email == "abc@gmail.com" ]];
then
        read -sp "Enter your password:" pass
        if [[ $pass == "admin@123" ]];
        then
                echo -e "\nSuccessfully logged in"
        else
                echo -e "\nIncorrect Password"
        fi
else
        echo "Please enter the correct Email ID"
fi


Output1:
Enter your Email:
abc@gmail.com
Enter your password:
Successfully logged in

Output2:
Enter your Email:
abc@gmail.com
Enter your password:
Incorrect Password

Output3:
Enter your Email:
sudhan@gmail.com
Please enter the correct Email ID
