#! /bin/bash

services=("httpd" "docker" "jenkins")

for service in "${services[@]}";
do
        if systemctl is-active --quiet "$service";
        then
                echo "Service $service is running"
        else
                echo "Service $service is not running"
        fi
done


Output1:
Service httpd is running
Service docker is not running
Service jenkins is not running

Output2:
Service httpd is running
Service docker is running
Service jenkins is not running
