#! /bin/bash

echo "Total memory: $(free -m | awk '/Mem/ {print $2 " MB"}')"

echo "Used memory: $(free -m | awk '/Mem/ {print $3 " MB"}')"

echo "Free memory: $(free -m | awk '/Mem/ {print $4 " MB"}')"

Output:
Total memory: 912 MB
Used memory: 262 MB
Free memory: 121 MB
