#! /bin/bash
name=""

if [[ -n $name ]];
then
        echo "It is non-empty string"
else
        echo "It is an empty string"
fi


Output:
It is an empty string

----------------------------------------------------------------

#! /bin/bash
name="Sudhan"

if [[ -n $name ]];
then
        echo "It is non-empty string"
else
        echo "It is an empty string"
fi


Output:
It is non-empty string

----------------------------------------------------------------

#! /bin/bash
name=" "

if [[ -n $name ]];
then
        echo "It is non-empty string"
else
        echo "It is an empty string"
fi


Output:
It is non-empty string
