#! /bin/bash
abc="Sudhar"
xyz="Sudheer"
if [[ $abc == $xyz ]];
then
        echo "Both are same"
else
        echo "Both are not same"
fi

Output:
Both are not same

------------------------------------------------------------------

#! /bin/bash
abc="Sudhar"
xyz="Sudheer"
if [[ $abc != $xyz ]];
then
        echo "The condition is satisfied"
else
        echo "The condition is not satisfied"
fi

Output:
The condition is satisfied

------------------------------------------------------------------

#! /bin/bash
abc=22
xyz=44
if [[ $abc -eq $xyz ]];
then
        echo "abc is equal to xyz"
else
        echo "abc is not equal to xyz"
fi

Output:
abc is not equal to xyz

------------------------------------------------------------------

#! /bin/bash
abc=22
xyz=44
if  [[ $abc -lt $xyz ]];
then
        echo "abc is lesser than xyz"
elif [[ $abc -gt $xyz ]];
then
        echo "abc is greater than xyz"
else
        echo "abc and xyz are equal"
fi

Output:
abc is lesser than xyz

------------------------------------------------------------------

#! /bin/bash
abc=22
xyz=10
if  [[ $abc -lt $xyz ]];
then
        echo "abc is lesser than xyz"
elif [[ $abc -gt $xyz ]];
then
        echo "abc is greater than xyz"
else
        echo "abc and xyz are equal"
fi

Output:
abc is greater than xyz

------------------------------------------------------------------

#! /bin/bash
abc=10
xyz=10
if  [[ $abc -lt $xyz ]];
then
        echo "abc is lesser than xyz"
elif [[ $abc -gt $xyz ]];
then
        echo "abc is greater than xyz"
else
        echo "abc and xyz are equal"
fi

Output:
abc and xyz are equal

------------------------------------------------------------------

#! /bin/bash
abc=10 (or) 55
xyz=10
if [[ $abc -ge $xyz ]];
then
        echo "abc is greater than or equal to xyz"
else
        echo "abc is lesser than xyz"
fi

Output:
abc is greater than or equal to xyz

------------------------------------------------------------------

#! /bin/bash
abc=5
xyz=10
if [[ $abc -le $xyz ]];
then
        echo "abc is lesser than or equal to xyz"
else
        echo "abc is greater than xyz"
fi

Output:
abc is lesser than or equal to xyz
