#! /bin/bash
echo "Username:"
read user
read -sp "Password:" pass

if [[ $user == "Sudharsan" && $pass == "admin@123" ]];
then
        echo -e "\nLogin Successful!"
else
        echo -e "\nPlease use valid credentials"
fi

Output1:
Username:
Sudharsan
Password: 
admin@123
Login Successful!

Output2:
Username:
Sudhan
Password:
admin@123
Please use valid credentials

Output3:
Username:
Sudharsan
Password:
sudheeer@123
Please use valid credentials

Output4:
Username:
Sudhan
Password:
sudheeer@12345
Please use valid credentials

-------------------------------------------------------------------------

#! /bin/bash
echo "Username:"
read user
read -sp "Password:" pass

if [[ $user == "Sudharsan" || $pass == "admin@123" ]];
then
        echo -e "\nLogin Successful!"
else
        echo -e "\nPlease use valid credentials"
fi


Output1:
Username:
Sudharsan
Password: 
admin@123
Login Successful!

Output2:
Username:
Sudhan
Password:
admin@123
Login Successful!

Output3:
Username:
Sudharsan
Password:
sudheeer@123
Login Successful!

Output4:
Username:
Sudhan
Password:
sudheeer@12345
Please use valid credentials
