#! /bin/bash
file_path="/root/linux/aws.txt"

if [[ -e $file_path ]];
then
        echo "File exists"
else
        echo "File does not exist"
fi

Output:
File exists

--------------------------------------------------------------

#! /bin/bash
file_path="/root/linux/gcp.jpg"

if [[ -e $file_path ]];
then
        echo "File exists"
else
        echo "File does not exist"
fi

Output:
File does not exist

--------------------------------------------------------------

#! /bin/bash
file_path="/root/linux/azure.pdf"

if [[ -e $file_path ]];
then
        echo "File exists"
else
        echo "File does not exist"
fi

Output:
File exists

--------------------------------------------------------------

#! /bin/bash
echo "Enter the File Path:"
read file_path

if [[ -e $file_path ]];
then
        echo "File exists"
else
        echo "File does not exist"
fi

Output1:
Enter the File Path:
/root/linux/aws.txt
File exists

Output2:
Enter the File Path:
/root/linux/gcp.pdf
File does not exist
