#! /bin/bash
echo "Enter the File Path:"
read file_path

if [[ -f $file_path ]];
then
        echo "File exists"
else
        echo "File does not exist"
fi

Output1:
Enter the File Path:
/root/linux/aws.txt
File exists

Output2:
Enter the File Path:
/rootlinux/devops
File does not exist

------------------------------------------------------------------

#! /bin/bash
echo "Enter the File Path:"
read file_path

if [[ -d $file_path ]];
then
        echo "Directory exists"
else
        echo "Directory does not exist"
fi

Output1:
Enter the File Path:
/root/linux/devops
Directory exists

Output2:
Enter the File Path:
/root/linux/aws.txt 
Directory does not exist
